apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hz8qcdy55-nodejs 
  janus-idp.io/tekton: hz8qcdy55-nodejs
  backstage.io/kubernetes-id: hz8qcdy55-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hz8qcdy55-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml