apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hz8qcdy55-nodejs
  janus-idp.io/tekton: hz8qcdy55-nodejs
  backstage.io/kubernetes-id: hz8qcdy55-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hz8qcdy55-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
